### PR TITLE
Cache arch and platform property values

### PR DESCRIPTION
**Pull request by mattrepl**
The `arch` and `platform` properties are used to calculate the hash value for `Function` instances. Presently, the values for these properties are constructed every time the property is accessed. This PR adds caching for the values of both properties which results in a speedup of the call to `__hash__`.

### CODE REVIEW

**Comment by plafosse** [comment]
Good idea, I'll accept this after I do some testing with it. Thank you.

**Comment by plafosse** [comment]
Have you signed the contribution license agreement? https://binary.ninja/cla.pdf  It just says that you have the rights to the code you're submitting and you're contributing the code to Binary Ninja. Please email to info@vector35.com.

**Comment by mattrepl** [comment]
Hey, thanks, sounds good. Yep, I have already signed and submitted the agreement. Was a few months ago, IIRC.

**Comment by joshwatson** [comment]
This does have the side effect of violating the read-only restriction of the `arch` property

**Comment by mattrepl** [comment]
Hmm, I’d have to check PEPs to determine if that’s a violation of idiom.

Similar caching is currently done in ‘BasicBlock’ for the ‘arch’ and ‘function’ read property methods.

**Comment by plafosse** [comment]
Yeah, we don't do that since there are a lot of items that would need to be populated and it would slow down instance creation time. I like your fix.  Even though the property is marked as read only this is only to help people not shoot themselves in the foot. By adding a cached internal class variable yes we do slightly open the user up to shoot themselves in the foot, but I believe that risk is minimal and worth the speed gain from your code. Thanks again for the submission.

**Pull request merged**
