### PR TITLE
Fix enum of DirectoryNameField to FormInputFieldType.DirectoryNameFor…

### PR DESCRIPTION
**Pull request by Herz3h**
…mField

### CODE REVIEW

**Comment by psifertex** [comment]
Thanks! I realize this is a very trivial PR, but would you mind submitting a CLA as described in https://github.com/Vector35/binaryninja-api#contributing

**Comment by Herz3h** [comment]
Is an electronic signature enough for the CLA pdf ? Also is it an interactive pdf or gotta get a pdf editor ?

**Comment by plafosse** [comment]
Yes electronic signature is perfect. Thanks!

**Comment by plafosse** [comment]
Thanks for this. This issue is fixed in latest dev. I don't think we ever got a CLA otherwise I would have just accepted the PR.

**Pull request closed without merging**
