### PR TITLE
add StructureBuilder missing python methods

### PR DESCRIPTION
**Pull request by rbran**

### CODE REVIEW

**Comment by rbran** [comment]
Could the non-mutable setters be problematic? What if the user hold a reference to the builder (or internals) before a setter call?

Maybe a code like this could cause problems:
```rust
let builder: StructureBuilder = todo!();
let members = builder.members();
builder.clear_members();
for member in members.iter() {
 ...
}
```

This could be solved by having all the setters functions require `&mut self` and return an Array tied to the self lifetime. Or simply clone all the members and return a `Vec<StructureMember>` instead.

**Comment by KyleMiles** [comment]
This isn't building locally for me... Complaining about `CoreArrayWrapper` not accepting a lifetime parameter. Not sure why it works in CI, though. I'll look into this more later.

**Comment by rbran** [comment]
This was written before the GAT PR, I'll fix this.

**Comment by rbran** [comment]
@KyleMiles Fixed.

**Pull request merged**
