### PR TITLE
Fix typo in binaryview.py

### PR DESCRIPTION
**Pull request by Vasco-jofra**

### CODE REVIEW

**Comment by KyleMiles** [comment]
I'm going to go ahead and fix this outside of this pull request, but I'll make sure you give you the contribution credit @Vasco-jofra.

**Comment by KyleMiles** [comment]
Here: https://github.com/Vector35/binaryninja-api/commit/ef10818632b8a7373307fc436e95ca9220aae5cf

**Comment by Vasco-jofra** [comment]
@plafosse You're right, the `0x` was the problem and not the `hex`. I tested it, but saw a 0x<decimal_addr> and my mind just assumed it was hexadecimal. My bad

**Comment by plafosse** [comment]
No worries we got it fixed :)

**Pull request closed without merging**
