### PR TITLE
vars_read and vars_written property for HighLevelILInstruction

### PR DESCRIPTION
**Pull request by corinnedixon**
I was hoping to add these MLIL properties into HLIL as well. Let me know if there are any other HLIL Operations that should be included.

### CODE REVIEW

**Comment by plafosse** [comment]
Thank you for your contribution! Unfortunately we're in the middle of a big refactor to this code, so we're probably not going to accept this code as it will be much cleaner in the new version of the code. :)

**Comment by cetfor** [comment]
Hey Peter, do you know if this refactor something you're planning for v2.5 or a later release?

**Comment by psifertex** [comment]
The refactor is planned for 3.0 which is the very next release.

**Comment by plafosse** [comment]
Again thanks for the PR. This feature now exists in the dev version

**Pull request closed without merging**
