### PR TITLE
BinaryView.get_view_of_file Fix

### PR DESCRIPTION
**Pull request by joshwatson**
`BinaryViewType.get_view_of_file` wasn't properly handling .bndb files

### CODE REVIEW

**Comment by joshwatson** [comment]
Okay, something is definitely going on somewhere else, because I'm still seeing errors, and it's because `BinaryView.get_view_of_type('ELF')` is returning a strange half-raw,half-ELF view for me that prints `<BinaryView: start 0x8000, len 0x9038>` and `bv.view` is `Hex:Raw`

**Comment by joshwatson** [comment]
Welp, that is very weird, because I definitely didn't mess with that, haha. It must have been my editor or something?

**Comment by joshwatson** [comment]
Fixed the new line issue

**Comment by plafosse** [comment]
Thank you @joshwatson!

**Pull request merged**
