### PR TITLE
Fixing various MIPS relocation issues

### PR DESCRIPTION
**Pull request by Whurbin**
Fixes various MIPS relocation issues.

1. Implicit addends in MIPS do not seem to be honored. Adding the addend to the target address to fix relocation target.

2. It is supposed to be the case that R_MIPS_HI16 relocations are followed by one or more R_MIPS_LO16 relocations. This is not always the case when certain compiler optimizations are enabled. Removing this requirement and fulfilling the relocation regardless of the preceding relocation.

3. Adding support for the following relocations:
- R_MIPS_HIGHEST
- R_MIPS_HIGHER
- R_MIPS_GPREL16
- R_MIPS_GPREL32
- (R_MIPS_64 << 8) | R_MIPS_REL32 (i.e. 0x1203)

### CODE REVIEW

**Comment by Whurbin** [comment]
This patch should fix the following issue(s):
https://github.com/Vector35/binaryninja-api/issues/5876

**Comment by plafosse** [comment]
Thanks for the PR! Do you happen to have a binary which contains these relocations that you can share?

**Comment by zznop** [comment]
This PR has been accepted and included in builds >= `4.2.6325-dev`. Thank you for the contribution.

**Comment by zznop** [comment]
@Whurbin - this PR caused a regression in handling `LO16` and `HI16` relocation types with certain binaries. I am going to revert back to the old code for those relocation types for now. Do you have a binary that we can use to investigate this behavior:

> It is supposed to be the case that R_MIPS_HI16 relocations are followed by one or more R_MIPS_LO16 relocations. This is not always the case when certain compiler optimizations are enabled. Removing this requirement and fulfilling the relocation regardless of the preceding relocation.

I also sent you a message on Slack.

**Pull request closed without merging**
