### PR TITLE
Fix struct member confidence

### LINKED ISSUE #4543: StructureMember in the C++ API discards type confidence info available from the core
On the API side, the `StructureMember` is defined as: https://github.com/Vector35/binaryninja-api/blob/adb819496e5e447b7acf5336ffe5d0a18a03c448/binaryninjaapi.h#L8078-L8085. However, on the core side, we can see that `BNStructureMember` actually has a confidence info available: https://github.com/Vector35/binaryninja-api/blob/adb819496e5e447b7acf5336ffe5d0a18a03c448/binaryninjacore.h#L2116-L2124

### LINKED ISSUE #4703: Typo in call to _get_python_environment within PythonScriptingProvider._python_bin property
**Version and Platform (required):**
- Binary Ninja Version: latest
- OS: MacOS
- OS Version: Ventura
- CPU Architecture: M1 Max

**Bug Description:**
In python/scriptingprovider.py, within PythonScriptingProvider._python_bin, there is the following line:

	python_env = self._get_python_environemnt(using_bundled_python=not python_lib)

The call to `_get_python_environment()` is misspelled.

### PR DESCRIPTION
**Pull request by SmoothHacker**
Fixes #4543 so that all StructMember structs in the C++ API now have type confidence that core provides.
Also fixes #4703 as it was a simple typo in the PythonScriptingProvider.

### CODE REVIEW

**Comment by SmoothHacker** [comment]
I also noticed that the StructureBuilder functions in the C++ API that return a StructureMember does not contain the access and scope members vars that core provides. Is this also a bug? I could take care of it in this PR.

https://github.com/Vector35/binaryninja-api/blob/049692f154af2c50e88ddb77edd64cb70f15ac12/binaryninjaapi.h#L8384-L8391

https://github.com/Vector35/binaryninja-api/blob/049692f154af2c50e88ddb77edd64cb70f15ac12/type.cpp#L2461-L2473

**Comment by xusheng6** [comment]
I will review the PR in the following days.

**Comment by SmoothHacker** [comment]
I found 8 places where the `access` and `scope` field were missing

**Comment by xusheng6** [comment]
> I added the field updates in all the places where BNStructureMember is created.

LGTM -- I will test it tomorrow!

**Comment by xusheng6** [comment]
Thx @SmoothHacker !

**Pull request merged**
